#!/bin/sh -x


ARGS=5

if [ "$#" -ne 5 ]; then
    echo "Usage: $(basename $0) method type ident token auth" 1>&2
    exit 1
fi

METHOD=$1
TYPE=$2
IDENT=$3
TOKEN=$4
AUTH=$5

case "$TYPE" in
	dns-01)
		case "$METHOD" in
			begin)
				lindns set "$IDENT" TXT _acme-challenge "$AUTH"
			;;
			done)
				/etc/init.d/nginx configtest &&
					/etc/init.d/nginx reload
			;;
			failed)
				echo "$0: failed" 1>&2
				exit 1
			;;
			*)
				echo "$0: invalid method: $METHOD" 1>&2
				exit 1
		esac
		;;
	*)
		echo "$0: unsupported challenge: $TYPE" 1>&2
		exit 1
		;;
esac
