global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: '{{ monitoring.prom.external_label }}-monitor'

scrape_configs:
  - job_name: 'node'
    scheme: https
    metrics_path: /node_exporter/metrics
    basic_auth:
      username: prometheus
      password: "{{ monitoring.prom.basic_auth }}"
    static_configs:
      - targets:
        {% for t in monitoring.prom.targets.node_exporter %}
        - {{ t }}
        {% endfor %}
