global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: '{{ monitoring.external_label }}-monitor'

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
