route:
  group_by:
    - alertname
  receiver: pushover
receivers:
  - name: pushover
    pushover_configs:
      - user_key: {{ monitoring.alertmanager.pushover.user_key }}
        token: {{ monitoring.alertmanager.pushover.token }}
