#!/bin/sh -e

bat_tag='{"name":"battery"'

part() {
	local name=$1
	local text="$2"
	echo "{\"name\":\"${name}\",\"markup\": \"none\",\"full_text\": \"${text}\"}"
}

brightness() {
	local d=/sys/class/backlight/intel_backlight
	local cur=$(cat $d/brightness)
	local max="$(cat $d/max_brightness)"
	echo "scale=0; $cur * 100 / $max" | bc
}

while read line; do
	bri_tag=$(part brightness "BRI $(brightness)%")
	echo "${line}" | sed "s#${bat_tag}#${bri_tag},${bat_tag}#"
done
